version: '3.9'

services:
  opal_api:
    image: opal
    build: .
    env_file:
      - .env
    environment:
      - OPALIZERENV=dev
    command: bash -c "
      uvicorn opalizer.main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug"
    volumes:
      - ./opalizer:/home/code/opalizer
      - ./tests:/home/code/tests
      - ./alembic:/home/code/alembic
    ports:
      - "8000:8000"
    depends_on:
      - opal_db

  opal_db:
    image: opal_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pass
    # healthcheck:
    #   test:
    #     [
    #         "CMD-SHELL", "pg_isready -d opal -U usr"
    #     ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
networks:
  opal:
    external: false
