[dev]
dynaconf_merge = true

[dev.app]
name =  "Opal Dev"
version = "0.0.1"

[dev.server]
log_level = "debug"
reload = true
cors_origins = ["http://0.0.0.0:3000", "http://0.0.0.0:4200"]

[dev.db]
username = "usr"
password = "pass"
host = "opal_db"
name = "opal"
echo = true
